spring:
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7076

management:
  endpoints:
    web:
      exposure:
        include: "*"
