spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training
    username: postgres
    password: Cloud@123$

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7074
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
